### ISSUE TITLE
Idea: attrs parameter for unmount

### ISSUE THREAD

**Issue by mikehwagz** [estrattonbailey/picoapp#8]
Hey Eric 👋

Been loving picoapp! So far I've really only encountered one challenge which is the desire to have certain components persist across `unmount` and `mount` calls (i.e. like a navigation component that persists across PJAX page transitions).

After reading over the source code more closely, I realized that calling `unmount` only actually unmounts the components that are no longer in the DOM. I'm assuming the goal here was to address challenges similar to the one I described above, but depending on the PJAX solution and page transition animation, components within the previous page might still be in the DOM when `unmount` is called. Instead of the `!document.documentElement.contains(node)` condition, what if `unmount` accepted an `attrs` parameter — just like `mount`?

This would achieve a few things:

1) Make the `unmount` function more predictable, only unmounting components mounted using the specified attribute(s) or `data-component` by default
2) Give the developer more control over how components are `unmounted` (i.e. persistent components could use `data-ui` which could be mounted once on load `app.mount(['data-ui', 'data-component'])` and ignored on subsequent `unmount`/`mount` calls)

What do you think? I have a working version of this locally. Would be happy to make a PR if you'd like to take a look.

**Comment by estrattonbailey** [comment]
Solved in #9
